audit_header: false
title: The Base Template
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name:
  license_number:
  about_markdown: |

  market:
  brand:
  brokerage:
  address:
  phone:
  phone_type:
  phone2:
  phone2_type:
  email:
  url:
  first_CTA_text: Home Evaluation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
  phone_CTA: true
  VR_form:
welcome_headline: Join Our -- MARKET -- VIP List
welcome_text_markdown: |
  Our mission at -- CLIENT BRAND -- is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title:
  categories: News & Politics
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
images:
  client_headshot_path: '/img/headshot.jpg'
  hero_logo_path: '/img/logo.png'
  logo_width_number: 40
  hero_text: Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: '/img/background.jpg'
brand_color: '#094264'
theme_color: '#094264'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
